//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim.Portarias.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sim.Portarias.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Portarias] WHERE (([Indice] = @Original_Indice)).
        /// </summary>
        internal static string DeleteQuery {
            get {
                return ResourceManager.GetString("DeleteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [PortariasServidor] ([Nome], [Inserido] , [Bloqueado]) VALUES (@Servidor, @Inserido, @Bloqueado).
        /// </summary>
        internal static string InsertNewServidor {
            get {
                return ResourceManager.GetString("InsertNewServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Portarias] ([Numero], [Data], [Tipo], [Resumo], [Servidor], [Link], [Publicado], [Cadastro], [Atualizado], [Excluido]) VALUES (@Numero, @Data, @Tipo, @Resumo, @Servidor, @Link, @Publicado, @Cadastro, @Atualizado, @Excluido).
        /// </summary>
        internal static string InsertQuery {
            get {
                return ResourceManager.GetString("InsertQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Portarias WHERE (Excluido = 0) ORDER BY Data DESC.
        /// </summary>
        internal static string SelectAllReg {
            get {
                return ResourceManager.GetString("SelectAllReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT        Indice, Numero, Data, Tipo, Resumo, Servidor, Link, Publicado, Cadastro, Atualizado, Excluido
        ///FROM            Portarias
        ///WHERE        (Excluido = 0) AND (Numero = @Numero) AND (Data = @Data).
        /// </summary>
        internal static string SelectByNumber {
            get {
                return ResourceManager.GetString("SelectByNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Portarias WHERE (Excluido = 0) AND ((Numero BETWEEN @NumeroI AND @NumeroF) AND (Data BETWEEN @Data1 AND @Data2) AND (Tipo LIKE @Tipo) AND (Resumo LIKE @Resumo) AND (Servidor LIKE @Nome)) ORDER BY Data, Numero.
        /// </summary>
        internal static string SelectByParam {
            get {
                return ResourceManager.GetString("SelectByParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Portarias WHERE (Excluido = 1) ORDER BY Data DESC.
        /// </summary>
        internal static string SelectInactive {
            get {
                return ResourceManager.GetString("SelectInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Nome FROM PortariasServidor WHERE (Bloqueado = 0) ORDER BY Nome.
        /// </summary>
        internal static string SelectServidores {
            get {
                return ResourceManager.GetString("SelectServidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Portarias] SET [Numero] = @Numero, [Data] = @Data, [Tipo] = @Tipo, [Resumo] = @Resumo, [Servidor] = @Servidor, [Link] = @Link, [Publicado] = @Publicado, [Cadastro] = @Cadastro, [Atualizado] = @Atualizado, [Excluido] = @Excluido WHERE ([Indice] = @Original_Indice).
        /// </summary>
        internal static string UpDateQuery {
            get {
                return ResourceManager.GetString("UpDateQuery", resourceCulture);
            }
        }
    }
}
