//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Login.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8271_128x128 {
            get {
                object obj = ResourceManager.GetObject("_8271_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Account
        ///WHERE        (Indice = @Indice) AND (Identificador = @ID).
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO
        ///Account (Identificador, Senha, Nome, Email, Conta, Cadastro, Atualizado, Bloqueado) VALUES
        ///(@Identificador, @Senha, @Nome, @Email, @Conta, @Cadastro, @Atualizado, @Bloqueado).
        /// </summary>
        internal static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Indice], [Identificador], [Senha], [Nome], [Email], [Conta], [Cadastro], [Atualizado], [Bloqueado] FROM [Account] ORDER BY Nome.
        /// </summary>
        internal static string SelectAllUsers {
            get {
                return ResourceManager.GetString("SelectAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT        Indice, Identificador, Senha, Nome, Email, Conta, Cadastro, Atualizado, Bloqueado
        ///FROM            Account
        ///WHERE        (Conta &lt;= @Acesso) ORDER BY Identificador.
        /// </summary>
        internal static string SelectUserByAcesso {
            get {
                return ResourceManager.GetString("SelectUserByAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT        Indice, Identificador, Senha, Nome, Email, Conta, Cadastro, Atualizado, Bloqueado
        ///FROM            Account
        ///WHERE        (Identificador = @ID) AND (Senha = @Senha) AND (Bloqueado = 0).
        /// </summary>
        internal static string SelectUserLogin {
            get {
                return ResourceManager.GetString("SelectUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE       Account
        ///SET                Senha = @Senha, Nome = @Nome, Email = @Email, Conta = @Conta, Atualizado = @Atualizado, Bloqueado = @Bloqueado
        ///WHERE        (Indice = @Indice) AND (Identificador = @ID).
        /// </summary>
        internal static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
    }
}
